"""
Auto-generated MCP tools from browser recording.
Generated by AutoMCP.

Note: This file is loaded via exec() by server.py which provides:
- mcp: FastMCP instance for tool registration
- httpx: HTTP client library
- get_request_cookies: Function to get cookies for a URL
- get_csrf_token: Function to get CSRF token
"""

import httpx
from session_utils import get_request_cookies, get_csrf_token

# mcp is provided by server.py via execution_context - do not instantiate here



# Tool: Retrieves configuration data that categorizes and describes various cookies for privacy compliance and consent management.
@mcp.tool()
async def get_cookie_compliance_categories():
    """
    Retrieves configuration data that categorizes and describes various cookies for privacy compliance and consent management.
    This tool is used to identify how different cookies are classified (e.g., essential, performance, advertising) 
    according to Atlassian's privacy standards.
    """
    url = "https://atlassian-cookies--categories.us-east-1.prod.public.atl-paas.net/categories_COOKIE.json"
    cookies = get_request_cookies(url)
    headers = {
        "referer": "https://trello.com/",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
        "sec-ch-ua-platform": '"macOS"',
        "sec-ch-ua": '"Chromium";v="145", "Not:A-Brand";v="99"',
        "sec-ch-ua-mobile": "?0"
    }

    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(
                url, 
                cookies=cookies, 
                headers=headers,
                timeout=30.0
            )
            response.raise_for_status()
            return response.json()
    except httpx.HTTPStatusError as e:
        return f"HTTP error occurred while retrieving cookie categories: {e.response.status_code} - {e.response.text}"
    except Exception as e:
        return f"An unexpected error occurred while retrieving cookie categories: {str(e)}"


# Tool: Retrieves feature flag configurations and experimental toggles for the Trello web application interface.
@mcp.tool()
async def get_trello_feature_flags(client_sdk_key: str = "trello_web"):
    """
    Retrieves feature flag configurations and experimental toggles for the Trello web application interface.
    This tool helps in identifying which experimental features are currently enabled for the user session.

    Args:
        client_sdk_key (str): The client SDK identifier, defaults to 'trello_web'.
    """
    url = f"https://api.atlassian.com/flags/api/v2/frontend/clientSdkKey/{client_sdk_key}"
    cookies = get_request_cookies(url)
    headers = {
        "x-api-key": "1f24403e-f053-43de-b063-e20b357a8f63",
        "x-client-version": "0.0.0-development",
        "x-client-name": "feature-gate-js-client",
        "content-type": "application/json"
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, headers=headers, cookies=cookies, timeout=30.0)
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {
                "error": f"HTTP error {e.response.status_code} while fetching feature flags",
                "details": e.response.text
            }
        except Exception as e:
            return {"error": f"Unexpected error: {str(e)}"}


# Tool: Fetches feature flag configurations and experiment toggles for a Trello user based on their account and device metadata.
@mcp.tool()
async def get_feature_flags(atlassian_account_id: str, namespace: str = "trello_web", is_desktop: bool = False, is_touch: bool = False, locale: str = "en-US"):
    """
    Fetches feature flag configurations and experiment toggles for a Trello user based on their Atlassian account and device metadata.

    Args:
        atlassian_account_id: The user's Atlassian account ID.
        namespace: The configuration namespace (e.g., 'trello_web').
        is_desktop: Whether the request is coming from a desktop environment.
        is_touch: Whether the request is coming from a touch-enabled device.
        locale: The locale of the user (e.g., 'en-US').
    """
    url = "https://api.atlassian.com/flags/api/v2/configurations"
    cookies = get_request_cookies(url)
    
    payload = {
        "namespace": namespace,
        "identifiers": {
            "atlassianAccountId": atlassian_account_id
        },
        "metadata": {
            "isDesktop": is_desktop,
            "isTouch": is_touch,
            "locale": locale
        },
        "dsc": get_csrf_token()
    }

    async with httpx.AsyncClient() as client:
        try:
            # We use json=payload to ensure the correct Content-Type header and JSON encoding
            response = await client.post(url, json=payload, cookies=cookies)
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error {e.response.status_code}: {e.response.text}"}
        except Exception as e:
            return {"error": str(e)}


# Tool: Retrieves the structural data of a specific Trello board, including its lists and all associated cards with their labels.
@mcp.tool()
async def get_board_structure(board_short_link: str):
    """
    Retrieves the structural data of a specific Trello board, including its lists and all associated cards with their labels.

    Args:
        board_short_link: The short link (ID) of the board (e.g., 'a7UxwGZY').
    """
    url = "https://trello.com/gateway/api/graphql?operationName=quickload:TrelloCurrentBoardListsCards"
    cookies = get_request_cookies(url)
    
    query = "query TrelloCurrentBoardListsCards($id:TrelloShortLink!){trello{__typename boardByShortLink(shortLink:$id)@optIn(to:\"TrelloBoard\"){id __typename lists(first:-1){__typename edges{__typename node{id __typename cards(first:-1)@optIn(to:\"TrelloListCards\"){__typename edges{__typename node{id __typename closed labels(first:-1){__typename edges{__typename node{id __typename color name objectId}}}objectId...on TrelloCard{isTemplate}}}}}}}}}}"
    
    payload = {
        "query": query,
        "variables": {"id": board_short_link},
        "operationName": "TrelloCurrentBoardListsCards",
        "dsc": get_csrf_token()
    }
    
    headers = {
        "accept": "application/json",
        "content-type": "application/json",
        "x-trello-operation-name": "quickload:TrelloCurrentBoardListsCards",
        "x-trello-operation-source": "quickload"
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                url, 
                json=payload, 
                cookies=cookies, 
                headers=headers,
                timeout=30.0
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error {e.response.status_code}", "message": e.response.text}
        except Exception as e:
            return {"error": "Internal Error", "message": str(e)}


# Tool: Retrieves feature flag and A/B test variations tailored to the user's account attributes and session context.
@mcp.tool()
async def get_experiment_values(
    atlassian_account_id: str,
    analytics_anonymous_id: str,
    target_app: str = "trello_web",
    custom_attributes: dict = None
):
    """
    Retrieves feature flag and A/B test variations tailored to the user's account attributes and session context.

    Args:
        atlassian_account_id: The Atlassian account ID of the user.
        analytics_anonymous_id: The anonymous analytics identifier.
        target_app: The application identifier (e.g., 'trello_web').
        custom_attributes: A dictionary containing user context such as locale, enterprise status, or cohort information.
    """
    url = "https://api.atlassian.com/flags/api/v2/frontend/experimentValues"
    cookies = get_request_cookies(url)
    
    headers = {
        "sec-ch-ua-platform": '"macOS"',
        "referer": "https://trello.com/",
        "x-api-key": "1f24403e-f053-43de-b063-e20b357a8f63",
        "x-client-version": "0.0.0-development",
        "x-client-name": "feature-gate-js-client",
        "content-type": "application/json"
    }

    # Prepare payload with identifiers and custom attributes
    payload = {
        "identifiers": {
            "atlassianAccountId": atlassian_account_id,
            "analyticsAnonymousId": analytics_anonymous_id
        },
        "customAttributes": custom_attributes or {},
        "targetApp": target_app,
        "dsc": get_csrf_token()
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                url, 
                headers=headers, 
                json=payload, 
                cookies=cookies,
                timeout=30.0
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error occurred: {e.response.status_code}", "details": e.response.text}
        except Exception as e:
            return {"error": f"An unexpected error occurred: {str(e)}"}


# Tool: Retrieves the count of unread notifications for the current user to display in the interface.
@mcp.tool()
async def get_notifications_count(grouped: bool = True, notification_filter: str = "all"):
    """
    Retrieves the count of unread notifications for the current user to display in the interface.

    Args:
        grouped (bool): Whether to group the notification counts.
        notification_filter (str): Filter for the notifications, such as 'all'.
    """
    url = "https://trello.com/1/members/me/notificationsCount"
    params = {
        "grouped": str(grouped).lower(),
        "filter": notification_filter
    }
    cookies = get_request_cookies(url)
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, params=params, cookies=cookies)
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return f"Error fetching notification count: {e.response.status_code} - {e.response.text}"
        except Exception as e:
            return f"An unexpected error occurred: {str(e)}"


# Tool: Retrieves a paginated list of the user's unread notifications along with detailed metadata for the associated cards and boards.
@mcp.tool()
async def get_unread_notification_groups(limit: int = 10, skip: int = 0, read_filter: str = "unread"):
    """
    Retrieves a paginated list of the user's unread notifications along with detailed metadata for the associated cards and boards.

    Args:
        limit: The number of notification groups to retrieve (default: 10).
        skip: The number of notification groups to skip for pagination (default: 0).
        read_filter: Filter for notifications by read status (default: 'unread').
    """
    url = "https://trello.com/1/members/me/notificationGroups"
    params = {
        "limit": limit,
        "skip": skip,
        "read_filter": read_filter,
        "card_fields": "id,badges,cardRole,checkItemStates,closed,cover,dateLastActivity,desc,descData,due,dueComplete,dueReminder,email,idAttachmentCover,idBoard,idChecklists,idLabels,idList,idMembers,idMembersVoted,idShort,isTemplate,manualCoverAttachment,name,pos,shortLink,shortUrl,start,subscribed,url",
        "card_board_fields": "id,name,prefs,subscribed,url"
    }
    
    cookies = get_request_cookies(url)
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(
                url, 
                params=params, 
                cookies=cookies,
                headers={"content-type": "application/json"}
            )
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error occurred: {e.response.status_code}", "detail": e.response.text}
        except Exception as e:
            return {"error": f"An unexpected error occurred: {str(e)}"}


# Tool: Retrieves a Trello member's profile data and detailed licensing/subscription information for all their associated organizations.
@mcp.tool()
async def get_member_organizations(member_id: str):
    """
    Retrieves a Trello member's profile data and detailed licensing/subscription information for all their associated organizations.

    Args:
        member_id: The unique ID or username of the Trello member.
    """
    url = f"https://trello.com/1/member/{member_id}"
    params = {
        "fields": "id,idPremOrgsAdmin",
        "organizations": "all",
        "organization_fields": "id,availableLicenseCount,displayName,idEnterprise,maximumLicenseCount,offering,premiumFeatures"
    }
    cookies = get_request_cookies(url)
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, params=params, cookies=cookies)
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return f"Error fetching member organization data: {e.response.text}"
        except Exception as e:
            return f"An unexpected error occurred: {str(e)}"


# Tool: Retrieves detailed metadata, member information, and subscription status for a specific Trello workspace.
@mcp.tool()
async def get_workspace_details(workspace_id: str):
    """
    Retrieves detailed metadata, member information, and subscription status for a specific Trello workspace.

    Args:
        workspace_id: The ID or name of the Trello workspace to retrieve details for.
    """
    url = f"https://trello.com/1/organization/{workspace_id}"
    params = {
        "fields": "id,desc,displayName,idEnterprise,idEntitlement,memberships,name,offering,prefs,premiumFeatures,website",
        "enterprise": "true",
        "members": "all",
        "member_fields": "id,fullName,memberType,nonPublic",
        "paidAccount": "true",
        "paidAccount_fields": "standing"
    }
    cookies = get_request_cookies(url)
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, params=params, cookies=cookies)
            response.raise_for_status()
            return response.json()
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error occurred: {e.response.status_code}", "details": e.response.text}
        except Exception as e:
            return {"error": f"An unexpected error occurred: {str(e)}"}


# Tool: Initiates or checks a request for the user to gain permission to access a specific Trello board.
@mcp.tool()
async def request_board_access(board_id: str):
    """
    Initiates or checks a request for the user to gain permission to access a specific Trello board.

    Args:
        board_id (str): The unique identifier or short link of the Trello board.
    """
    url = f"https://trello.com/1/board/{board_id}/requestAccess"
    cookies = get_request_cookies(url)
    headers = {
        "x-trello-operation-name": "RequestAccessPage",
        "x-trello-operation-source": "graphql",
        "referer": f"https://trello.com/b/{board_id}/testboard"
    }
    
    async with httpx.AsyncClient() as client:
        try:
            response = await client.get(url, cookies=cookies, headers=headers)
            response.raise_for_status()
            try:
                return response.json()
            except ValueError:
                return response.text
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP {e.response.status_code}", "message": e.response.text}
        except Exception as e:
            return {"error": "Internal Error", "message": str(e)}


# Tool: Registers a client-side session or user interaction event for Atlassian product analytics.
@mcp.tool()
async def register_atlassian_analytics_session(
    client_key: str,
    source_type: str = "javascript-client",
    source_version: str = "3.26.0",
    timestamp: str = "1769957265379",
    session_id: str = "7c520333-2327-4860-b530-df00e29e29c8",
    event_count: str = "102",
    is_gzipped: str = "1"
):
    """
    Registers a client-side session or user interaction event for Atlassian product analytics.
    
    This tool is used to log telemetry data and track user engagement sessions within Atlassian products.
    It captures metadata about the client environment, session identifiers, and event sequencing.

    Args:
        client_key: The specific client identifier used for analytics tracking (k).
        source_type: The platform or environment sending the analytics (st).
        source_version: The version of the analytics client library (sv).
        timestamp: The timestamp of the registration event (t).
        session_id: A unique identifier for the current user session (sid).
        event_count: The incremental count of events recorded in the session (ec).
        is_gzipped: Indicates if the data payload is compressed (gz).
    """
    url = "https://xp.atlassian.com/v1/rgstr"
    params = {
        "k": client_key,
        "st": source_type,
        "sv": source_version,
        "t": timestamp,
        "sid": session_id,
        "ec": event_count,
        "gz": is_gzipped
    }
    
    cookies = get_request_cookies(url)
    # Include CSRF token as required for POST requests
    data = {"dsc": get_csrf_token()}
    
    headers = {
        "sec-ch-ua-platform": "\"macOS\"",
        "referer": "https://trello.com/",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36"
    }

    async with httpx.AsyncClient() as client:
        try:
            response = await client.post(
                url, 
                params=params, 
                cookies=cookies, 
                data=data, 
                headers=headers,
                timeout=30.0
            )
            response.raise_for_status()
            try:
                return response.json()
            except Exception:
                return response.text
        except httpx.HTTPStatusError as e:
            return {"error": f"HTTP error occurred: {e.response.status_code}", "details": e.response.text}
        except Exception as e:
            return {"error": f"An unexpected error occurred: {str(e)}"}


# Tool: Retrieves a list of stock photos from an Unsplash collection for the user to select as a Trello board background.
@mcp.tool()
async def get_unsplash_collection_photos(collection_id: str, per_page: int = 30, order_by: str = "latest", page: int = 1):
    """
    Retrieves a list of stock photos from an Unsplash collection for the user to select as a Trello board background.

    Args:
        collection_id: The unique identifier for the Unsplash collection (e.g., '317099').
        per_page: Number of photos to retrieve per page (default 30).
        order_by: How to sort the results, such as 'latest'.
        page: The page number for pagination.
    """
    url = f"https://trello.com/proxy/unsplash/collections/{collection_id}/photos"
    params = {
        "per_page": per_page,
        "order_by": order_by,
        "page": page
    }
    headers = {
        "accept-version": "v1"
    }
    cookies = get_request_cookies(url)

    try:
        async with httpx.AsyncClient() as client:
            response = await client.get(
                url, 
                params=params, 
                headers=headers, 
                cookies=cookies,
                timeout=30.0
            )
            response.raise_for_status()
            return response.json()
    except httpx.HTTPStatusError as e:
        return {"error": f"HTTP error {e.response.status_code}: {e.response.text}"}
    except Exception as e:
        return {"error": f"An unexpected error occurred: {str(e)}"}
